### ISSUE TITLE
Handling protobuf Structs

### ISSUE THREAD

**Issue by pawmart** [micro/examples#36]
Hi there,

Has anyone done micro requests where you want to accept protobuf Struct of ANY JSON structure, please?

I have a JSON multidimensional structure which I want to capture -> modify -> return...

I thought the best candiate for this would be `google.Struct` type, but can't seem to define it so it unmarshals correctly.

```
syntax = "proto3";

package go.micro.srv.config;
option go_package = "config";

import "google/protobuf/struct.proto";

service Configs {
    rpc Run(Message) returns (Message);
}

message Message {
    google.protobuf.Struct state = 4;
}

message Message {
    google.protobuf.Struct state = 2;
}

```

**Comment by asim** [comment]
It is unclear to me how this works. It seems rather complex. Could it be that it relies on jsonpb? We do not use jsonpb for unmarshalling. 

Out of curiosity are you using micro at a company?

**Comment by asim** [comment]
I think the approach is incorrect. If you need multi-dimensional data that could be any form of json you have two optons. 

1. Make it explicitly clear as a field in the proto e.g Data, Payload, Blob, whatever it may be as bytes.
2. Set the content type of what's being sent to json so that it's explicitly encoded as json, then on the service side make the request thats accepted by  `map[string]interface{}`.

This example may help you to implement the second https://github.com/micro/examples/tree/master/noproto

Which company? Can I add it to the users page?

**Comment by pawmart** [comment]
I quite like your suggestions.

1. This would be ideal, however I am not sure if I am able to send bytes in json e.g. via micro web? 
And another issue would be decoding and encoding at a consumer level which wont be 'go'. Maybe serialise to string or something?

2. This looks like feasable, but we end up with 'no proto' definition for this endpoint so documentation and clarify suffers ;/

**Comment by asim** [comment]
You're looking at a sort of edge case I don't have a good answer for. You can define any request type you like, what's forwarded from the web dashboard or from the micro api is always usually json rather than protobuf so it's likely the service gets json and tries to decode to that. Your field in a proto type does not have to be bytes, it can be string if you need it to be.

**Comment by pawmart** [comment]
ok, i have managed to represent json as string and all works fine, thank you for your time @asim
